// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using crud.Data;

#nullable disable

namespace crud.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517071248_PrimeiraMigration")]
    partial class PrimeiraMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("crud.Models.Empresa", b =>
                {
                    b.Property<int>("cd_empresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("cd_empresa"));

                    b.Property<string>("cd_cnpj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ds_endereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nm_razao_social_empresa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("cd_empresa");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("crud.Models.Funcionario", b =>
                {
                    b.Property<int>("cd_funcionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("cd_funcionario"));

                    b.Property<string>("cd_cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("cd_empresa")
                        .HasColumnType("int");

                    b.Property<string>("nm_funcionario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("cd_funcionario");

                    b.HasIndex("cd_empresa");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("crud.Models.Funcionario", b =>
                {
                    b.HasOne("crud.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("cd_empresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });
#pragma warning restore 612, 618
        }
    }
}
